

- name: Create Supervisor config for bench restart
  ansible.builtin.template:
    src: restart.conf.j2
    dest: /etc/supervisor/conf.d/restart.conf
    mode: "0644"
  notify: restart supervisor
  tags: supervisor