# frappe.yml
---
# This Playbook would install deps, deploy mariadb for frappe
- name: Install dependencies and deploy MariaDB for Frappe
  hosts: k8s
  roles:
   - role: timezone
   - role: apt
   - role: mariadb
   - role: user
   - role: node
   - role: supervisor
   - role: frappe
