# tasks file for project
- name: Init bench
  become: true
  become_user: "{{ user_name }}"
  environment:
    PATH: "/home/{{ user_name }}/.local/bin:/home/{{ user_name }}/.nvm/versions/node/v{{ node_version }}/bin:{{ ansible_env.PATH }}"
  ansible.builtin.shell: |
    /bin/bash -c "source /home/{{ user_name }}/.nvm/nvm.sh && \
    bench init {{ frappe_bech_name }} --frappe-branch {{ frappe_version }}"
  changed_when: false
  args:
    chdir: "/home/{{ user_name }}/"
  async: 600
  poll: 20

- name: Install apps in bench
  become: true
  become_user: "{{ user_name }}"
  environment:
    PATH: "/home/{{ user_name }}/.local/bin:/home/{{ user_name }}/.nvm/versions/node/v{{ node_version }}/bin:{{ ansible_env.PATH }}"
  ansible.builtin.shell: |
    bench get-app {{ item.app_name }} --branch {{ item.app_branch }}
  changed_when: false
  args:
    chdir: "/home/{{ user_name }}/{{ frappe_bech_name }}"
  loop: "{{ apps }}"
  tags: get_apps
  async: 600
  poll: 20

- name: Add apps to apps.txt
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: |
    ls -1 /home/{{ user_name }}/{{ frappe_bech_name }}/apps > /home/{{ user_name }}/{{ frappe_bech_name }}/sites/apps.txt
  changed_when: false
  tags: add_apps
  async: 600
  poll: 20

- name: Setup redis
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: |
    bench setup redis
  changed_when: false
  args:
    chdir: "/home/{{ user_name }}/{{ frappe_bech_name }}"
  async: 600
  poll: 20
  tags: setup_redis

- name: Setup supervisor
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: |
    bench setup supervisor --yes
  changed_when: false
  args:
    chdir: "/home/{{ user_name }}/{{ frappe_bech_name }}"
  async: 600
  poll: 20
  tags: setup_supervisor

- name: Setup nginx
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: |
    bench setup nginx --yes --log_format ""
  changed_when: false
  args:
    chdir: "/home/{{ user_name }}/{{ frappe_bech_name }}"
  async: 600
  poll: 20
  tags: setup_nginx

- name: Setup Production
  ansible.builtin.shell: |
    bench setup production {{ user_name }} --yes
  changed_when: false
  args:
    chdir: "/home/{{ user_name }}/{{ frappe_bech_name }}"
  tags: setup_production
  async: 600
  poll: 20

- name: Change bench directory's ownership and mode
  ansible.builtin.file:
    path: /home/{{ user_name }}/
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'
  tags: change_permissions
