---
# tasks file for frappe



- name: Allow frappe user to run supervisorctl without password
  copy:
    dest: /etc/sudoers.d/frappe_supervisor
    content: "frappe ALL=(ALL) NOPASSWD:/usr/bin/supervisorctl"
    mode: 0440


- name: Create Script to install Frappe Bench
  become: true
  become_user: "{{ user_name }}"
  template:
    src: install.sh.j2
    dest: /home/{{ user_name }}/install.sh
    mode: "0755"

# - name: Install yarn
#   community.general.npm:
#     executable: /home/{{ user_name }}/.nvm/versions/node/v{{ node_version }}/lib/node_modules/npm
#     path: /home/{{ user_name }}/
#     name:
#       - yarn
#     global: true
#     state: present

- name: Install frappe-bench
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.command:
    cmd: pip install frappe-bench
    chdir: /home/{{ user_name }}

- name: Init bench
  become: true
  become_user: "{{ user_name }}"
  environment:
    PATH: "/home/{{ user_name }}/.local/bin:/home/{{ user_name }}/.nvm/versions/node/v{{ node_version }}/bin:{{ ansible_env.PATH }}"
  shell: |
    /bin/bash -c "source /home/{{ user_name }}/.nvm/nvm.sh && \
    bench init {{ frappe_bech_name }} --frappe-branch {{ frappe_version }}"
  args:
    chdir: "/home/{{ user_name }}/"
  async: 1800
  poll: 10



- name: Install apps in bench
  become: true
  become_user: "{{ user_name }}"
  environment:
    PATH: "/home/{{ user_name }}/.local/bin:/home/{{ user_name }}/.nvm/versions/node/v{{ node_version }}/bin:{{ ansible_env.PATH }}"
  shell: |
    bench get-app {{ item.app_name }} --branch {{ item.app_branch }}
  args:
    chdir: "/home/{{ user_name }}/{{ frappe_bech_name }}"
  loop: "{{ apps }}"
  tags: get_apps


- name: Add apps to apps.txt
  become: true
  become_user: "{{ user_name }}"
  shell: |
    ls -1 /home/{{ user_name }}/{{ frappe_bech_name }}/apps > /home/{{ user_name }}/{{ frappe_bech_name }}/sites/apps.txt
  tags: add_apps


- name: Create Site
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.command:
    cmd: /home/{{ user_name }}/.local/bin/bench new-site {{ item.site_name }} --admin-password {{ item.admin_password }} --mariadb-root-password {{ db_root_password }}
    chdir: /home/{{ user_name }}/{{ frappe_bech_name }}/
    creates: /home/{{ user_name }}/{{ frappe_bech_name }}/sites/{{ item.site_name }}
  loop: "{{ sites }}"
  tags: create_site

- name: Install apps in site
  become: true
  become_user: "{{ user_name }}"
  environment:
    PATH: "/home/{{ user_name }}/.local/bin:{{ ansible_env.PATH }}"
  shell: |
    bench --site {{ item.site_name }} install-app {{ item.apps }} && \
    bench --site {{ item.site_name }} migrate
  args:
    chdir: "/home/{{ user_name }}/{{ frappe_bech_name }}"
  loop: "{{ sites }}"
  tags: apps_in_sites
