---
# tasks file for node

- name: Install nvm
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: >
    curl "{{ nvm_url }}" | bash
    creates=/home/{{ user_name }}/.nvm/nvm.sh
  changed_when: false


- name: Install node and yarn
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: >
    /bin/bash -c "source /home/{{ user_name }}/.nvm/nvm.sh
    && nvm install {{ node_version }}
    && nvm use {{ node_version }}
    && npm install -g yarn"
  changed_when: false


    