---
# tasks file for node

- name: Download NVM installer
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh"
    dest: /tmp/install_nvm.sh
    mode: "0755"

- name: Install NVM
  ansible.builtin.shell: |
    set -o pipefail
    bash /tmp/install_nvm.sh
  changed_when: false

- name: Install node and yarn
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: |
    /bin/bash -c "source /home/{{ user_name }}/.nvm/nvm.sh
    && nvm install {{ node_version }}
    && nvm use {{ node_version }}
    && npm install -g yarn"
  changed_when: false
